#!/bin/bash

IFACE=en0
LISTEN_ADDRESS=192.168.0.13

pushd tftp; make; popd



function cleanup_children {
  pkill -TERM -P $$
}

trap "cleanup_children" EXIT
trap "cleanup_children" CHLD

dnsmasq -d -C dnsmasq.conf -i $IFACE &
